python run_files/ppo_reg_adapt/run_ppo_reg_adapt_ant.py
python run_files/ppo_reg_adapt/run_ppo_reg_adapt_half.py
python run_files/ppo_reg_adapt/run_ppo_reg_adapt_hopper.py
python run_files/ppo_reg_adapt/run_ppo_reg_adapt_walker.py
python run_files/ppo_reg_adapt/run_ppo_reg_adapt_idp.py
python run_files/ppo_reg_adapt/run_ppo_reg_adapt_ipsu.py
